### ISSUE TITLE
AttributeError: unexpected attribute 'row_headers' to DataTable, similar attributes are index_header

### ISSUE THREAD

**Issue by aaron8tang** [verybadsoldier/backtrader_plotting#12]
Traceback (most recent call last):
  File "/crossover_strategy.py", line 131, in <module>
    cerebro.plot(b)
  File "D:\devhome\anaconda3\lib\site-packages\backtrader\cerebro.py", line 996, in plot
    plotter.show()
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 218, in show
    filename = self._generate_output(self._fp)
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 228, in _generate_output
    return self._show_tabs(fp, filename)
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 271, in _show_tabs
    p_analyzers = self._get_analyzer_tab(fp)
  File "backtrader_plotting\backtrader_plotting\bokeh\bokeh.py", line 287, in _get_analyzer_tab
    table_header, elements = self._tablegen.get_analyzers_tables(analyzer, strategy, params)
  File "backtrader_plotting\backtrader_plotting\bokeh\datatable.py", line 75, in get_analyzers_tables
    elems.append(DataTable(source=cds, columns=columns, width=self._scheme.table_width, height=column_height, row_headers=False))
  File "D:\devhome\anaconda3\lib\site-packages\bokeh\models\widgets\tables.py", line 494, in __init__
    super(TableWidget, self).__init__(**kw)
  File "D:\devhome\anaconda3\lib\site-packages\bokeh\model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "D:\devhome\anaconda3\lib\site-packages\bokeh\core\has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "D:\devhome\anaconda3\lib\site-packages\bokeh\core\has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'row_headers' to DataTable, similar attributes are index_header

bokeh 0.12.5 has removed this property.

The mis-named property DataTable.row_header has been deprecated. This property confusingly controlled the presence of an index column in a DataTable. Now, use the index_position property to specify where an index column should be located in the table (use None to suppress the index column).

see:
https://bokeh.pydata.org/en/latest/docs/releases/0.12.15.html#datatable

**Comment by aaron8tang** [comment]
I switch back to master, it works.
