### ISSUE TITLE
Unsupported plot object

### ISSUE THREAD

**Issue by RusEu** [verybadsoldier/backtrader_plotting#33]
Traceback (most recent call last):
  File "strategy.py", line 188, in <module>
    cerebro.plot(bokeh)
  File "/home/drus/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "/usr/lib/python3.7/site-packages/backtrader_plotting-0.5.3-py3.7.egg/backtrader_plotting/bokeh/bokeh.py", line 398, in plot
  File "/usr/lib/python3.7/site-packages/backtrader_plotting-0.5.3-py3.7.egg/backtrader_plotting/bokeh/bokeh.py", line 229, in _blueprint_strategy
  File "/usr/lib/python3.7/site-packages/backtrader_plotting-0.5.3-py3.7.egg/backtrader_plotting/bokeh/figure.py", line 167, in plot
Exception: Unsupported plot object: <class '__main__.MMARStrategy'>

```
data = bt.feeds.GenericCSVData(dataname='/home/drus/Projects/ib_dl/ib_dl/HC-EQQQ@BVME-1M-20190325-20190918-ib.csv', **dkwargs)
cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=45, name="15min_bar")    
cerebro.addstrategy(MMARStrategy)
cerebro.broker = bt.brokers.BackBroker(slip_perc=0.0) 
cerebro.broker.setcash(10000)
cerebro.addsizer(LongOnly)
cerebro.broker.setcommission(commission=0.02, commtype=bt.CommInfoBase.COMM_FIXED)
cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name="mySharpe", riskfreerate=0.001)
cerebro.signal_accumulate(False)
cerebro.broker.set_shortcash(False)

print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

cerebro.run()
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

bokeh = Bokeh(style='bar', plot_mode='single')
cerebro.plot(bokeh)
```

**Comment by verybadsoldier** [comment]
Sorry, I cannot reproduce. There are too many missing parts that I had to guess. Please provide full runnable source code to reproduce.

**Comment by verybadsoldier** [comment]
No further information provided
