### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by krema** [verybadsoldier/backtrader_plotting#35]
hi, 

I just tested your lib for optimization plotting but somehow it fails. Any idea? 

      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
          result = await result
        File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
          yielded = self.gen.throw(*exc_info)  # type: ignore
        File "/usr/local/lib/python3.7/site-packages/bokeh/server/views/doc_handler.py", line 56, in get
          session = yield self.get_session()
        File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
          value = future.result()
        File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
          yielded = self.gen.throw(*exc_info)  # type: ignore
        File "/usr/local/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 79, in get_session
          session = yield self.application_context.create_session_if_needed(session_id, self.request)
        File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
          value = future.result()
        File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
          yielded = self.gen.send(value)
        File "/usr/local/lib/python3.7/site-packages/bokeh/server/contexts.py", line 222, in create_session_if_needed
          self._application.initialize_document(doc)
        File "/usr/local/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
          h.modify_document(doc)
        File "/usr/local/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
          self._func(doc)
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 40, in make_document
          model = self._build_optresult_model()
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 94, in _build_optresult_model
          model = column([selector, _get_model(0)])
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/bokeh/optbrowser.py", line 91, in _get_model
          return self._bokeh.plot_and_generate_optmodel(self._optresults[idx][0])
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 287, in plot_and_generate_optmodel
          return self.generate_model(0)
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/bokeh/bokeh.py", line 314, in generate_model
          meta = Div(text=metadata.get_metadata_div(figurepage.strategy))
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 91, in get_metadata_div
          md += _get_datas(strategy)
        File "/usr/local/lib/python3.7/site-packages/backtrader_plotting/html/metadata.py", line 39, in _get_datas
          'Time From:': bt.num2date(data.fromdate),
        File "/usr/local/lib/python3.7/site-packages/backtrader/utils/dateintern.py", line 165, in num2date
          ix = int(x)
      OverflowError: cannot convert float infinity to integer

**Comment by verybadsoldier** [comment]
Please provide a runnable minimal source code example that shows the problem

**Comment by takato3000** [comment]
Hi, I found the same issue.

I printed data.fromdate, it is -inf by default,and date.todate is inf.They can't be converted directly into integer.

I passed datetime arguments to them, they may help preventing this error.
`data = bt.feeds.PandasData(dataname=pd_data, fromdate=datetime.datetime(2020, 1, 1), todate=datetime.datetime(2020, 2, 1), name='XBTUSD')`

**Comment by verybadsoldier** [comment]
No further information provided. Feel free to reopen when information is available.
