### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by edwardyeung** [verybadsoldier/backtrader_plotting#44]
Traceback (most recent call last):
  File "C:/Users/YYCH/PycharmProjects/backtrader_practice/2020_03_09.py", line 207, in <module>
    cerebro.plot(b)
  File "D:\Anaconda3\lib\site-packages\backtrader\cerebro.py", line 996, in plot
    plotter.show()
  File "D:\Anaconda3\lib\site-packages\backtrader_plotting\bokeh\bokeh.py", line 461, in show
    model = self.generate_model(idx)
  File "D:\Anaconda3\lib\site-packages\backtrader_plotting\bokeh\bokeh.py", line 314, in generate_model
    meta = Div(text=metadata.get_metadata_div(figurepage.strategy))
  File "D:\Anaconda3\lib\site-packages\backtrader_plotting\html\metadata.py", line 91, in get_metadata_div
    md += _get_datas(strategy)
  File "D:\Anaconda3\lib\site-packages\backtrader_plotting\html\metadata.py", line 39, in _get_datas
    'Time From:': bt.num2date(data.fromdate),
  File "D:\Anaconda3\lib\site-packages\backtrader\utils\dateintern.py", line 165, in num2date
    ix = int(x)
OverflowError: cannot convert float infinity to integer

Process finished with exit code 1

Sample Data:
Date,Open,High,Low,Close,Adj Close,Volume
2017-03-20,196.500000,200.800003,196.500000,200.399994,183.332794,7978380
2017-03-21,200.600006,200.800003,198.600006,199.699997,182.692398,3655748
2017-03-22,196.800003,197.500000,195.699997,196.399994,179.673447,5325847
2017-03-23,196.000000,197.800003,196.000000,196.399994,179.673447,2405926
2017-03-24,196.699997,197.199997,195.500000,196.399994,179.673447,2084358
2017-03-27,195.500000,197.300003,194.399994,195.000000,178.392700,3444243
2017-03-28,196.199997,196.800003,195.100006,195.399994,178.758636,2145042
2017-03-29,196.600006,196.600006,194.199997,194.600006,178.026749,2645913
2017-03-30,194.600006,195.699997,194.399994,194.399994,177.843796,3158549
2017-03-31,196.000000,196.600006,194.899994,195.600006,178.941620,4445851
2017-04-03,196.300003,197.500000,195.600006,196.100006,179.399017,2974162
2017-04-05,197.000000,197.399994,195.699997,197.399994,180.588272,2602084
2017-04-06,196.000000,197.399994,195.699997,196.000000,179.307526,1935783
2017-04-07,195.699997,196.399994,193.800003,195.899994,179.216034,2499111
2017-04-10,196.100006,196.399994,194.500000,195.500000,178.850098,1803309
2017-04-11,195.899994,195.899994,193.399994,193.800003,177.294891,3571257

**Comment by edwardyeung** [comment]
OS: Windows 8
Python 32bit 3.7.4

**Comment by edwardyeung** [comment]
this data is downloaded from yahoo finance.
which is from https://finance.yahoo.com/quote/0388.hk/
data = bt.feeds.YahooFinanceCSVData(
        dataname=r".\datas\20170319-20200319-0388.HK.csv",
        fromdata=datetime.datetime(2017, 3, 19),
        todata=datetime.datetime(2020, 3, 19)

**Comment by verybadsoldier** [comment]
Please help me out by posting the full runnable code and attach the data file. Thank you.

**Comment by edwardyeung** [comment]
[practice.zip](https://github.com/verybadsoldier/backtrader_plotting/files/4364274/practice.zip)

**Comment by verybadsoldier** [comment]
Thank you. The issue is already fixed in branch `develop` please try that version.

**Comment by edwardyeung** [comment]
It works fine. Thanks for you help.
